import type { Metadata } from "next";
import { ArrowRight, BrainCircuit, CheckCircle2, Lightbulb, Sparkles } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { CTASection, FeatureCard, PageHero, SectionHeading } from "@/components/marketing/blocks";

export const metadata: Metadata = { title: "AI Learning | Hyle Edify", description: "Discover Hyle Edify's thoughtful approach to current and coming-soon AI learning support." };

export default function AiLearningPage() {
  return <><PageHero eyebrow="AI-powered learning" title="Technology that supports the teacher—and the learner." description="Hyle Edify is exploring AI thoughtfully, keeping current capabilities clear and future possibilities honest."><Link href="/courses" className="mt-8 inline-flex"><Button size="lg" variant="accent">Explore current learning <ArrowRight className="h-4 w-4" /></Button></Link></PageHero><section className="bg-white"><div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><div className="grid gap-6 lg:grid-cols-2"><div className="rounded-3xl border border-hyle-green/30 bg-[#f6faf8] p-8"><span className="inline-flex rounded-full bg-[#d9efc9] px-3 py-1 text-xs font-bold uppercase tracking-wider text-hyle-navy">Current</span><BrainCircuit className="mt-8 h-10 w-10 text-hyle-green" /><h2 className="mt-6 text-2xl font-bold text-hyle-navy">Learning signals you can use today.</h2><ul className="mt-6 grid gap-3 text-sm text-slate-600">{["Progress tracking for recorded lessons", "Resume from the latest video position", "Live and recorded course access", "A clear student learning dashboard"].map((item) => <li key={item} className="flex gap-2"><CheckCircle2 className="h-4 w-4 shrink-0 text-hyle-green" />{item}</li>)}</ul></div><div className="rounded-3xl border bg-hyle-navy p-8 text-white"><span className="inline-flex rounded-full border border-white/20 px-3 py-1 text-xs font-bold uppercase tracking-wider text-white/70">Coming soon</span><Sparkles className="mt-8 h-10 w-10 text-[#b6e993]" /><h2 className="mt-6 text-2xl font-bold">Future support, clearly labeled.</h2><p className="mt-4 leading-7 text-white/65">Planned capabilities may include personalized study support, smart practice tools, and AI learning assistance. These are not currently presented as live features.</p></div></div></div></section><section className="bg-[#f6faf8]"><div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><SectionHeading eyebrow="Our approach" title="Useful, human, and transparent." /><div className="mt-10 grid gap-4 md:grid-cols-3"><FeatureCard icon={Lightbulb} title="Useful first">Technology should make a learner's next step clearer, not add noise.</FeatureCard><FeatureCard icon={BrainCircuit} title="Teacher-supported">AI exploration complements thoughtful teaching rather than replacing it.</FeatureCard><FeatureCard icon={CheckCircle2} title="Transparent">Current functionality and future plans remain visibly separate.</FeatureCard></div></div></section><CTASection title="Start with the learning that exists today." text="Explore live and recorded Hyle Edify courses while future tools are being thoughtfully developed." /></>;
}

