import Link from "next/link";
import { ArrowLeft, Users } from "lucide-react";
import { Button } from "@/components/ui/button";

const placeholders = ["Faculty profile coming soon", "Official faculty profile", "Teaching team profile", "Faculty profile coming soon", "Official faculty profile", "Teaching team profile"];

export const metadata = { title: "Team | Hyle Edify", description: "Meet the Hyle Edify team. Official faculty profiles will be published as verified information becomes available." };

export default function TeamPage() {
  return <div className="bg-[#f6faf8]"><section className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8"><Link href="/" className="inline-flex items-center gap-2 text-sm font-semibold text-hyle-navy hover:text-hyle-green"><ArrowLeft className="h-4 w-4" />Back to home</Link><div className="mt-12 max-w-2xl"><p className="text-sm font-bold uppercase tracking-[0.18em] text-hyle-green">Meet the Hyle Edify team</p><h1 className="mt-3 text-4xl font-bold tracking-tight text-hyle-navy sm:text-5xl">The people behind the learning journey.</h1><p className="mt-5 text-lg leading-8 text-slate-600">Official faculty profiles are being prepared. We will publish names, photographs, qualifications, and experience only after verification.</p></div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{placeholders.map((item, index) => <article key={`${item}-${index}`} className="rounded-2xl border border-dashed bg-white p-6 transition hover:-translate-y-1 hover:shadow-lg"><div className="flex h-20 w-20 items-center justify-center rounded-2xl bg-[#eef6f9]"><Users className="h-8 w-8 text-hyle-green" /></div><p className="mt-7 font-semibold text-hyle-navy">{item}</p><p className="mt-2 text-sm text-slate-500">Designation, qualifications, experience, and official photo to be added.</p><span className="mt-4 inline-flex rounded-full bg-[#d9efc9] px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider text-hyle-navy">Coming soon</span></article>)}</div><div className="mt-12 rounded-2xl border bg-white p-6 text-sm leading-6 text-slate-600"><strong className="text-hyle-navy">Content note:</strong> This page intentionally uses placeholders until verified Hyle Edify team information is supplied.</div><Link href="/#contact" className="mt-8 inline-block"><Button variant="accent">Contact Hyle Edify</Button></Link></section></div>;
}
